### ISSUE TITLE
Cannot affect number of drops a plant gives in config [a17]

### ISSUE THREAD

**Issue by shadowbolt79** [AgriCraft/AgriCraft#1009]
I was fixing mystical agriculture plants in the config files. I got everything almost fixed, but the 5 tiers of inferium plants were totally messed up.

There seed items were not pointing to the correct seeds, tier 5 was named wrong so it wasn't even pulling the right kind of seed texture. Renamed the seeds and plants, and of course, the widely known spawning of plants in crop sticks. Fixed all of that.

However, the different tiers of inferium plants are supposed to drop different numbers of inferium essence. A 1,1,1 should drop their tier in essences. However, all plants, despite changing both min and max on higher tiers, drop the standard 1-5 number of drops. Attached is my config file for t5 inferium plants in case I am doing something wrong:

[tier5_inferium_plant.json](https://pastebin.com/aZYCy5E2)

**Comment by TokkenGmr** [comment]
Just as a heads up all the fixes that you made are on the current agriplants repo, and if I had to guess will be in the next release. As for the different tiers of inferium plants I have not tested changing the min or max product output. Will take a look at mine when I get home.

**Comment by shadowbolt79** [comment]
@TokkenGmr Typo still exists in your tier 5 inferium plants in two places. You added an extra n.

`"item": "mysticalagriculture:tier5_infernium_seeds",`
`"seed_texture": "mysticalagriculture:items/infernium_seeds",`

**Comment by TokkenGmr** [comment]
I did not make the JSON files for these seeds but you are correct it is an easy mistake to make, also that typo is fixed in the current [agriplants repo](https://github.com/AgriCraft/AgriPlants) it was corrected 6 days ago

**Comment by Meduris** [comment]
I also noticed the unchangeable amount of dropped essences today when trying to adjust the inferium seeds to act like when planted normally. Actually after changing the configs, I only got one essence at a time. With the default values, I got one to 5 essences at a time.

**Comment by shadowbolt79** [comment]
@TokkenGmr Ahh,right. But those two typos still exist in the current repo: https://github.com/TokkenGmr/AgriPlants/blob/master/mod_mysticalagriculture/plants/tier5_inferium_plant.json
The other things seem to have been fixed.

**Comment by TokkenGmr** [comment]
@shadowbolt79 Have a look right [here ](https://github.com/AgriCraft/AgriPlants/commit/33ff9c79e8ec114d0d7f4c681e5a1f31bce13110) is that not the correct information?

**Comment by shadowbolt79** [comment]
@TokkenGmr Ah, ok. That's where my confusion was.

**Comment by RlonRyan** [comment]
This looks like it has been resolved.

**Comment by shadowbolt79** [comment]
@RlonRyan when was this resolved?
