### ISSUE TITLE
Can't put mystical agriculture inferium seeds into agricraft crops Minecraft 1.12.2

### ISSUE THREAD

**Issue by Noobwiki** [AgriCraft/AgriCraft#1189]
In Minecraft 1.12.2 with forge 2.4.2.60, AgriCraft-2.12.0-1.12.0-a6 and mysticalagriculture-1.12-1.6.12, planting Mystical Agriculture inferium seeds into Agricraft crops doesn't work. No error log/ game won't crash, the cropsticks just don't take the seeds. Strangely enough there are .Jason files for mystical agriculture in the agricraft folder.

**Comment by darthvader45** [comment]
Is there one for inferium?  If not, simply make one using one of the others as a template, and then submit it as a pull request.  Should then be included in the next update.

**Comment by Noobwiki** [comment]
> 
> 
> Is there one for inferium? If not, simply make one using one of the others as a template, and then submit it as a pull request. Should then be included in the next update.

There are .Jason files for tier 1-5  inferium seeds but it still doesn't work. Hence my confusion.

**Comment by darthvader45** [comment]
Huh, maybe check the soil requirement in those files.  Might be different than the farmland you use.

**Comment by Noobwiki** [comment]
The .Jason says inferium seeds need farmland soil. Which is what i use. I mean that is just tilled dirt right? Light levels are also high enough and it is wartered.

**Comment by darthvader45** [comment]
Huh.  Might be a bug in the code.  @asiekierka Anything you can find?

**Comment by darthvader45** [comment]
Well, either you or someone else on the team who knows about this.

**Comment by asiekierka** [comment]
I'm not a developer of either, though?

**Comment by darthvader45** [comment]
Who is an Agricraft dev though?  I could try the other names under the @ symbol, like @sk89q, @kylev, and @crawford42

**Comment by asiekierka** [comment]
Everyone who is an AgriCraft dev is most likely already subscribed to this list. Please don't just ping random people who contributed to the project - that is poor form.

**Comment by remclave** [comment]
> The .Jason says inferium seeds need farmland soil. Which is what i use. I mean that is just tilled dirt right? Light levels are also high enough and it is wartered.

Farmland Soil and Tilled Dirt are two different blocks.

**Comment by chriss199815** [comment]
Are there any new News?

**Comment by Algester** [comment]
https://github.com/AgriCraft/AgriCraft/issues/1132
answer right here but I'm still testing it

**Comment by tlitookilakin** [comment]
Thank you, this worked just fine!

**Comment by hyperjoe** [comment]
Hopefully this can get fixed in the base mod so we don't have to keep making this change manually.

**Comment by BlueAngel87** [comment]
i donwloaded this mod today on 1.12.2 and i still have this issue. i am not good with config files oand those stuff, can i get some help on it?

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
