### ISSUE TITLE
Maybe water tank will cause game crash randomly (Ticking block entity)

### ISSUE THREAD

**Issue by catmunyi** [AgriCraft/AgriCraft#1392]
## Quick description

Just walk around to some areas or some time will cause crash .

## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft: 3.0.4
* InfinityLib: 2.0.5
* AgriCraft OptiFine Compat: 0.0.1 
* OptiFine: 1.16.5_HD_U_G8
* Pretty large modpack about 220 mods

## Steps to replicate the issue

1. walk around to some areas (cause game crash many times in same area or some time).

## Expectations and explanations

My friend is building a water tank at same time.
But won't crash looking water tank direction.
My friend did not crash when building the water tank, but other players nearby cause crash randomly(some player not crash).
## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Default
  * Modpack: Private
* What kind of server:
  * [ ] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [ ] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [X] Only an existing save

## Links to crash logs, stack traces, etc

* https://gist.github.com/catmunyi/a63496d51288329086a7988031da46d8

**Comment by InfinityRaider** [comment]
Is this a single tank or a multiblock setup?

**Comment by catmunyi** [comment]
Multiblock setup
![image](https://user-images.githubusercontent.com/5690971/128822313-f9b2d4b8-81a3-4aa9-bb16-22b8f8cea989.png)

**Comment by InfinityRaider** [comment]
Across multiple chunks i assume?

**Comment by Flatgub** [comment]
I've also encountered this issue, the tank was indeed build across multiple chunks (directly on the corner of four chunks specifically) and would crash anyone who looking at the water tank.

**Comment by Flatgub** [comment]
Yeah looking a little further into it, I'm sure the tanks being close to one another has nothing to do, but also noticed that this is already fixed on a dev branch! 👍

**Comment by Diversion98** [comment]
I see this issue is closed but I'm still getting crashes with tanks.

agricraft: 3.0.5-hotfix

crashlog: https://pastebin.com/jiDSrTkv

**Comment by InfinityRaider** [comment]
Well shit

**Comment by Diversion98** [comment]
need more information about this problem?

**Comment by InfinityRaider** [comment]
Perhaps, but I am quite sure it's caused by a tank having it's main tile (at min coordinates unloaded).
But then I don't understand why this keeps happening.

I will need to try to force chunk loading very low in dev to try to reproduce it.

**Comment by Diversion98** [comment]
so for now, i just use worldedit or something to take out the tanks?

**Comment by Rosted420** [comment]
Im having an issue where my game crashes from just searching up the water tank with JEI....

**Comment by InfinityRaider** [comment]
Open a new issue for that and include a crash report.

**Comment by Rosted420** [comment]
Sure thing
