### ISSUE TITLE
Greenhouses still spawn even with the setting set to 0

### ISSUE THREAD

**Issue by Peach774** [AgriCraft/AgriCraft#1459]
## Quick description
Greenhouses shouldnt spawn when the setting for irrigated greenhouses in the config is set to 0, but they still do.

## Related issues and searches
Greenhouse, config

## Mods and versions used
* Minecraft: 1.18.2
* AgriCraft: 1.18.2-3.1.1
* InfinityLib: 1.18.2-2.1.1

## Steps to replicate the issue
1. Set Irrigated Greenhouse in villages config to 0
2. Explore to locate a large village
3. Find a greenhouse where there should be none.
4. Profit?

## Expectations and explanations
I wanted to stop greenhouses spawning in villages but they continue spawning.

## Your environment

* How are you playing?
  * Operating System: Windows 10, Forge 40.1.47
  * Launcher: Curseforge
  * Modpack: Custom
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

**Comment by InfinityRaider** [comment]
I'll check it out, thanks

**Comment by InfinityRaider** [comment]
Fixed in https://github.com/InfinityRaider/InfinityLib/commit/ea692e8305749f5ad7fecf94111c65fc0df9dd28

**Comment by Pingu-Pox** [comment]
This is still happening on latest:
agricraft-1.18.2-3.1.4
infinitylib-2.1.4

![image](https://user-images.githubusercontent.com/21115660/187734780-a04f93b0-906e-4bc1-a63b-2f7518264dfd.png)
