### ISSUE TITLE
AgriCraft encountered an error during the common_setup event phase.

### ISSUE THREAD

**Issue by CSSkies** [AgriCraft/AgriCraft#1507]
## Quick description
AgriCraft encountered an error during the common_setup event phase.

## Mods and versions used
* Minecraft: 1.18.2 Forge v40.2.4
* AgriCraft:  agricraft-1.18.2-3.1.4.jar
* InfinityLib: infinitylib-2.1.4.jar

## Steps to replicate the issue
No steps. I only hit the launch button, and it failed during launch.

## Expectations and explanations
Failed during launch; error as above.

* Operating System: Windows 11
* Launcher: Minecraft
* Modpack: Custom
* 
* What kind of server:
* N/A
* Game Modes:
* N/A
* Save File:
* N/A

## Links to crash logs, stack traces, etc
https://pastebin.com/TfaZLiJp (crashlog)
https://pastebin.com/tX5KfYu5 (latest.log)

## Screenshots (or videos)
https://imgur.com/a/gkjNvN2

**Comment by Ketheroth** [comment]
update your create version please, then try again

**Comment by CSSkies** [comment]
Create is up-to-date.
I removed Create and all of its add-ons, and I launched just fine.
Adding back in Create, and only Create, brings back the error and the game fails to launch.

It seems AgriCraft/InfinityLib has an incompatibility with Create.

Bug:
AgriCraft has an incompatibility with Create.

Versions:
    Minecraft: 1.18.2 Forge v40.2.4
    AgriCraft: agricraft-1.18.2-3.1.4.jar
    InfinityLib: infinitylib-2.1.4.jar
    Create: create-1.18.2-0.5.1.b.jar

Error Message:
AgriCraft (agricraft) encountered an error during the common_setup event phase
java.lang.NoClassDefFoundError: com/simibubi/create/content/contraptions/components/structureMovement/MovementBehavior

That "com/simibubi/create/content/contraptions/components/structureMovement/MovementBehavior" looks like a directory, and if so, it seems to be from the Create mod, so it might not be an issue on your end.

**Comment by Ketheroth** [comment]
oh sorry, must I've missed it in the log, update to the last agricraft version (3.1.5). The crash should be fixed in this version

**Comment by CSSkies** [comment]
Still crashing. 

latest.log: https://pastebin.com/S4QJwnpJ
![image](https://github.com/AgriCraft/AgriCraft/assets/75306919/2c6e08a2-6824-4781-8cd1-1f22827729c6)

**Comment by Ketheroth** [comment]
:(
that's a bug on our end, they changed the name of things in their code so we will have to adapt

**Comment by Ketheroth** [comment]
woops I miss-clicked
